apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostNamespace
metadata:
  name: block-host-namespaces
  annotations:
    description: "Pod의 hostPID 및 hostIPC 사용을 차단합니다."
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - kube-flannel
      # 관측성 네임스페이스 제외
      # Prometheus/Grafana 설치 보장
      - monitoring
      - local-path-storage
