apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockLatestTag
metadata:
  name: block-latest-tag
  annotations:
    description: "latest 태그 또는 태그 미지정 컨테이너 이미지를 차단합니다."
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - kube-flannel
      # 관측성 네임스페이스 제외
      # Prometheus/Grafana 설치 보장
      - monitoring
      - local-path-storage
