apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: assign-run-as-non-root
  annotations:
    description: "securityContext.runAsNonRoot 가 없는 컨테이너에 true 를 자동 주입합니다."
spec:
  applyTo:
  - groups: [""]
    versions: ["v1"]
    kinds: ["Pod"]
  match:
    scope: Namespaced
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    - kube-flannel
    # 관측성 네임스페이스 제외
    # Grafana 스케줄링 보장
    - monitoring
  location: "spec.containers[name:*].securityContext.runAsNonRoot"
  parameters:
    assign:
      value: true
    pathTests:
    - subPath: "spec.containers[name:*].securityContext.runAsNonRoot"
      condition: MustNotExist
---
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: assign-read-only-root-filesystem
  annotations:
    description: "securityContext.readOnlyRootFilesystem 가 없는 컨테이너에 true 를 자동 주입합니다."
spec:
  applyTo:
  - groups: [""]
    versions: ["v1"]
    kinds: ["Pod"]
  match:
    scope: Namespaced
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    - kube-flannel
    # 관측성 네임스페이스 제외
    # Grafana 스케줄링 보장
    - monitoring
  location: "spec.containers[name:*].securityContext.readOnlyRootFilesystem"
  parameters:
    assign:
      value: true
    pathTests:
    - subPath: "spec.containers[name:*].securityContext.readOnlyRootFilesystem"
      condition: MustNotExist
---
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: assign-run-as-non-root-init
  annotations:
    description: "initContainer의 securityContext.runAsNonRoot 가 없는 경우 true 를 자동 주입합니다."
spec:
  applyTo:
  - groups: [""]
    versions: ["v1"]
    kinds: ["Pod"]
  match:
    scope: Namespaced
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    - kube-flannel
    # 관측성 네임스페이스 제외
    # Grafana 스케줄링 보장
    - monitoring
  location: "spec.initContainers[name:*].securityContext.runAsNonRoot"
  parameters:
    assign:
      value: true
    pathTests:
    - subPath: "spec.initContainers[name:*].securityContext.runAsNonRoot"
      condition: MustNotExist
---
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: assign-read-only-root-filesystem-init
  annotations:
    description: "initContainer의 securityContext.readOnlyRootFilesystem 가 없는 경우 true 를 자동 주입합니다."
spec:
  applyTo:
  - groups: [""]
    versions: ["v1"]
    kinds: ["Pod"]
  match:
    scope: Namespaced
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    - kube-flannel
    # 관측성 네임스페이스 제외
    # Grafana 스케줄링 보장
    - monitoring
  location: "spec.initContainers[name:*].securityContext.readOnlyRootFilesystem"
  parameters:
    assign:
      value: true
    pathTests:
    - subPath: "spec.initContainers[name:*].securityContext.readOnlyRootFilesystem"
      condition: MustNotExist
